# FROM: https://github.com/dperson/samba/blob/master/docker-compose.yml
version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /mnt
      - /mnt2
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: '-s "Mount;/mnt" -s "User Volume;/mnt2;yes;no;no;user" -u "user;pwd" -p'

networks:
  default: